### ISSUE TITLE
Exposing constructUrl as part of the official exports?

### ISSUE THREAD

**Issue by mnussbaumer** [imgeng/imageengine-react#3]
Hi, 

I was doing some work with creating custom loaders with Next.js' `Image` component and ran into the issue of creating the correct query strings for IE's urls. 

So instead of re-writing all that logic, I thought it would be useful to use the `constructUrl` function that this package has. While it's possible to import that by giving the correct path inside the `node_modules` folder, e.g:

`import { constructUrl } from "@imageengine/react/build/utils/index.js";`

It doesn't look that official. If for instance the underlying function names, or file structure changes the import would be broken. 

My thought was that if this was exposed as a normal export, then perhaps these sort of "helpers" could be packaged individually in another npm package. This `React Image` package could then use that lib, and anyone wanting to write a custom component, even outside of React, could choose to install that smaller utility package and benefit from having vetted, up to date, helpers. For instance if something would change in the `directives` that IE accepts itself, then it would be just a matter of updating those helpers since the logic to translate the set of directives into the query string would be responsibility of the package. It's not like there's a lot of upside, but seems like a good option to have nonetheless.

Anyway, for my immediate case just having it exported "officially" would work. Would this be something possible to do?
Thanks

**Comment by kamermans** [comment]
Hi @mnussbaumer, thanks for the input, it seems like a good idea.  We'll have a chat internally and see if this is something we'd like to implement!
